import type { Direction, MapId } from './world'

export type NpcId = 'kevin' | 'bendik' | 'oda' | 'nils' | 'magnus'
export type NpcDefinition = { id: NpcId; name: string; mapId: MapId; route: readonly (readonly [number, number])[]; facing: Direction; lines: string[]; shirt: number; hair: number; width: number; tall?: boolean; glasses?: boolean; beard?: boolean; longHair?: boolean; bald?: boolean; sport?: boolean; hawaii?: boolean }
export const NPCS: NpcDefinition[] = [
  { id: 'kevin', name: 'Kevin', mapId: 'havn', route: [[14,12]], facing: 'down', shirt: 0x527b98, hair: 0xd9b961, width: 8, glasses: true, lines: ['Velkommen! Trykk Enter eller menyknappen for å åpne sekken og fiskeboken. Piltastene velger, og E eller A bekrefter.', 'Vil du skifte farger? Garderoben står på soverommet i andre etasje hjemme. Ta trappen fra stuen!'] },
  { id: 'oda', name: 'Oda', mapId: 'havn', route: [[18,17],[19,17],[20,17],[19,17]], facing: 'left', shirt: 0x996979, hair: 0x322c35, width: 12, longHair: true, lines: ['Se etter bar jord! Med spaden i sekken kan du grave etter agn. Vend deg mot jordflekken og velg Grav.', 'Kisten oppe hjemme har plass til utstyret ditt. Åpne den, velg en kategori og flytt ting mellom sekk og kiste.'] },
  { id: 'magnus', name: 'Magnus', mapId: 'havn', route: [[26,20]], facing: 'left', shirt: 0xd78457, hair: 0x65483b, width: 12, bald: true, beard: true, hawaii: true, lines: ['For en dag å fiske på! Jeg har hørt om en discokveite som blinker i alle regnbuens farger. Den finnes ikke her ennå, men tenk for en fangst!', 'Én fisk til! Ryktet sier at en kokoslaks en dag kan dukke opp. Foreløpig er den bare en skrøne — hawaiiskjorten min er i alle fall klar!'] },
  { id: 'bendik', name: 'Bendik', mapId: 'skogstjern', route: [[12,18]], facing: 'right', shirt: 0x688463, hair: 0xccab61, width: 8, tall: true, glasses: true, beard: true, lines: ['Vend deg mot vannet og velg Fisk. Agnet velger du i sekken under Forbruk. Forskjellige agn lokker forskjellige fisk!', 'Fiskeboken husker artene du har oppdaget, og den minste og største fisken du har fanget. Gjedda liker sluk!'] },
  { id: 'nils', name: 'Nils', mapId: 'skogstjern', route: [[26,24],[27,24],[28,24],[29,24],[28,24],[27,24]], facing: 'right', shirt: 0x538baf, hair: 0xe0c36c, width: 10, sport: true, lines: ['Kom igjen, neste kast kan bli legendarisk! Jeg hørte om en rakettabbor som hopper over tretoppene. Den finnes ikke i vannet her ennå — bare i historiene!', 'Fisking er toppidrett! Noen snakker om en tordengjedde som får stanga til å dure. Bare et rykte foreløpig, men jeg trener til den dagen!'] },
]
