name: Publish Firestore rules

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - firestore.rules

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
      - name: Install Firebase CLI
        run: npm install --global firebase-tools
      - name: Publish rules
        run: firebase deploy --only firestore:rules --project fiskespillet-6319e --non-interactive
